### GENERAL SETTINGS ###

# Site settings
title: openbases-icons
description: "Open Bases Icons"
baseurl: "/openbases-icons" #important: start with /
url: ""

# An icon with a slightly higher chance of selection :)
favorite: "flaticon/in-the-zoo/penguin.svg"

# Build settings
markdown: kramdown
permalink: /:categories/:title

exclude: 
  - '.git'
  - '_site'
